version: '3.7'

services:

  react:
    container_name: wp-decoupled-sample-react
    build: test-app
    restart: always
    ports:
      - 3030:3000
    depends_on:
      - graphql

  graphql:
    container_name: wp-decoupled-sample-graphql
    build: graphql
    restart: always
    ports:
      - 4040:4000
    depends_on:
      - wordpress

  wordpress:
    container_name: wp-decoupled-sample-wordpress
    build: backend
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: "define( 'WP_ENVIRONMENT_TYPE', 'local' );"
    depends_on:
      - db


  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
